In [ ]:
my_dict = {} #empty dict

In [ ]:
my_dict = [{"a":1,"b":2,"c":3,"d":4},
            {"a":2,"d":2},
            {"y":3}]   # creating dict ker value and pair

In [ ]:
print(my_dict) # print dict

In [ ]:
combine_dict_values(my_dict)

In [ ]:
def combine_dict_values(args):
    result={}
    
    for d in args:
        print(d)
        print(type(d))
    
        for keys,values in d.items():
            print(keys)
            print(values)
    
            if keys in result:
                  result[keys] = result[keys]+[values]
            else:
                  result[keys]= [values]
            
    return result
    

In [ ]:
str_input=['anna,50,60,70','bill,50,60','cal,30,50,70']
print(str_input)

for grade in str_input:
    list1=grade.split(',')[1:]
    print(list1)
   # print(type(grade.split(',')))

new_grade=[float (grade) for grade in list1 ]
#        new_grage=[]
#        for grade in grade:
#            new_grade.append(float(grade))




In [ ]:
def fact(n):
    print(f"fact calling ,n={n}")

    if n == 1 :
        print("reached base case")
        return 1
    else:
        r=n*fact(n-1)
        print("return r")
        return(r)
    
print(fact(5))

In [ ]:
def sum_digits(n):
    s = 0
    while n:
        s += n % 10
        n //= 10
    return s        

In [ ]:
x = sum_digits(111)
print(x)

In [ ]:
# recusive
def digital_root(n):
    x = sum(int(digit) for digit in str(n))
    if x < 10:
        return x
    else:
        return digital_root(x)

In [ ]:
digital_root(999)

In [ ]:
sum1 = lambda x,y:x+y

In [ ]:
sum1(3,5)
list1=["10","20","20"]

In [ ]:
r = map(sum1,list1)
print(r)

In [ ]:
mylist=["10","20","20"]

for i in map(float,mylist):
    print(i)

In [ ]:
C = [39.2,36.5,37.3,38,37.8]
print(C)

In [ ]:
F = lambda (x:x(5/9)+32 ,C)
print(F)

In [ ]:
list(filter(lambda x:x%2 ==0,range(0,100)))

In [ ]:
my_list=[1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,0]
         

In [ ]:
mylist1.split('0')

In [ ]:
my_list=[1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,0]

def contiguous_subarry(lst):
    return len(max(''.join(map(str,lst)).split('0')))

In [ ]:
contiguous_subarry(my_list)

In [ ]:
#swap the max value in list with last index
lst1 =[1,2,7,30,8]
print(list1)

#lst1.index(max(lst1))

max_no=max(list1)
last_ele=list1[-1] # last elemet



In [ ]:
def swap_max_last_elements(in_list):
     
    max_no=max(in_list)
    max_index=in_list.index(max_no)
    last_ele= in_list[-1]
    
    in_list[max_index] =last_ele
    in_list[-1] = max_no
    
    return in_list    

In [ ]:
list2=[3,5,6,81,88,80,1]
swap_max_last_elements([3,5,6,81,88,80,1])


In [ ]:
#remove the dubicate elements in list
lst=[1,2,4,5,6,6,7,8]

In [ ]:
mylist = ["a", "b", "a", "c", "c"]
mylist = list(dict.fromkeys(mylist))
print(mylist) 

In [ ]:
# Example of the class in python

class Circle:
    def __init__(self,redius):
        self.r = redius
        
    def area(self):
        self.a = self.r**2*3.14
        return self.a
    
    def perimeter(self):
        self.p = self.a+slef.r    
        return self.p
           
    def sumr(self):
        return self.a+slef.p
    

In [ ]:
c1 =Circle(10)
c2 =Circle(2)

c1.area()
c2.area()




In [ ]:
import math
class Point:
    
    def __init__(self,x,y):
        self.X = x
        self.Y = y
    
    def length(self):
        return( math.sqrt(self.X**2+self.Y**2))
    
    def distance(self,other):
        dx = self.X = other.X
        dy = self.Y = other.Y
        return(math.sqrt(dx**2+dy**2))

In [ ]:
p1 = Point(2,3)
p2 = Point(4,10)

In [ ]:
p1.X
p1.Y

In [ ]:
p1.length()


In [ ]:
p2.length()
p2.length()

In [ ]:
p1.distance(p2)

In [ ]:
# empty class 
class Competitor: pass


In [ ]:
# setting attributes to obj
conor =Competitor()

In [ ]:
conor.name ="srinivas"
conor.age =27
conor.college = "CBIT"

conor.__dict__

In [ ]:
import math

math.cos(45)

In [ ]:
from math import sqrt
sqrt(2)

In [ ]:
from math import sqrt as sqt
sqt(2)


In [ ]:
# create 2D array
import numpy as np
arr = np.array([[1,2,4,5],
              [4,5,6,7]])
print(arr)

In [ ]:
arr1 =[1,1,3,4,5]
arr.shape
arr.ndim
arr.size
arr.dtype
arr.itemsize


In [ ]:
myarray =np.array(arr1)
myarray

In [2]:
import numpy as np
temp = np.arange(10,32,4)
temp
z = np.zeros((2,2))
z.dtype


dtype('float64')

In [ ]:
z = np.ones((2,2))
z.dtype


In [ ]:
#change type  from flot64 to int 16
z = np.ones((2,2),dtype=np.int16)
z.dtype

In [ ]:
z = np.empty((2,2))
z.dtype

In [ ]:
np.linspace(0,10,20)
np.linspace(0,10,20)

In [3]:
import numpy as np
arr = np.array([[1,2,4,5],
              [4,5,6,7]])
print(arr)

[[1 2 4 5]
 [4 5 6 7]]


In [4]:
# array sub seting 
arr[0,0]

1

In [5]:
import numpy as np
arr = np.array([[1,2,3,4],
              [5,6,7,8]])
print(arr)
arr2 = arr[:2,:3]   
print(arr2)
   

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [5 6 7]]
